#!/usr/bin/env python3

# Recovers the final game state from a sequence of moves.
#
# The moves can be passed as command line arguments, or, when no command
# line arguments are provided, read from standard input (which is useful to
# parse a transcript generated by arbiter.py.)

import sys
import zpo


def Main(input):
    state = zpo.GameState()
    for line in input:
        line = line.strip()
        if line == '' or line[0] == '#':
            continue
        move = zpo.ParseMove(line)
        if move is None:
            print(f'Unable to parse move: {move}', file=sys.stderr)
            sys.exit(1)
        if not move.IsValid(state):
            print(f'Invalid move: {move}', file=sys.stderr)
            sys.exit(1)
        move.Execute(state)
    for line in state.DebugOutput():
        print(line)


if __name__ == '__main__':
    Main(sys.argv[1:] if len(sys.argv) > 1 else sys.stdin)
