#!/usr/bin/env python3

# Recovers the final game state from a sequence of moves.
#
# The moves can be passed as command line arguments, or, when no command
# line arguments are provided, read from standard input (which is useful to
# parse a transcript generated by arbiter.py.)

from collections import defaultdict
import re
import sys
import zpo

from math import inf

def Main(input):
    seen = defaultdict(list)
    state = zpo.GameState()
    for i, line in enumerate(input):
        line = line.strip()
        if line == '' or line[0] == '#':
            continue
        move = zpo.ParseMove(line)
        if move is None:
            print(f'Unable to parse move: {move}', file=sys.stderr)
            sys.exit(1)
        if not move.IsValid(state):
            print(f'Invalid move: {move}', file=sys.stderr)
            sys.exit(1)
        move.Execute(state)
        seen[state.Encode(reduce_turn=True)].append(i)

    # Print final state
    for line in state.DebugOutput():
        print(line)
    w = state.Winner()
    print('Winner:', 'none' if w is None else ['red', 'blue'][w])

    # Print information about repeated states
    first_repeat = inf
    max_repeat = 0
    for turns in sorted(seen.values(), key=lambda v: len(v), reverse=True):
        if len(turns) <= 1:
            break
        first_repeat = min(first_repeat, turns[1])
        max_repeat = max(max_repeat, len(turns))

    print('Simple state string:', state.Encode())
    print('Compact state string:', state.EncodeCompact())

    if first_repeat < inf:
        print('First repetition at turn:', first_repeat)
        print('Maximum number of repetitions:', max_repeat)


if __name__ == '__main__':
    Main(sys.argv[1:] if len(sys.argv) > 1 else sys.stdin)
